name: Archive docs
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 21 */2 *' # run every other month at an odd time to avoid burdening the server
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # see https://github.com/actions/checkout
      - name: Set up Go
        uses: actions/setup-go@v5 # note: automatically caches dependencies
        with:
          go-version: "1.22"
      - name: Build bin/spider_urls
        run: make bin/spider_urls
      - name: Run spider
        run: make data/url_list.tsv
      - name: Build bin/archive
        run: make bin/archive
      - name: Archive site
        run: make data/site.tar.gz
      - name: create release
        run: gh release create $(date "+%Y-%m-%d") data/site.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication
        # Note: `gh` is included in ubuntu-latest; see
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
